version: '3.8'

services:
  app:
    build: .
    ports: 
    - 3333:3333
    depends_on:
      - database
  
  database:
    image: postgres:14.2
    environment:
      POSTGRES_USER: marcelo
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: contele_db
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
