version: '3.8'

services:
  database:
    image: postgres:14.2
    container_name: database_contele
    environment:
      POSTGRES_USER: marcelo
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: contele_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app_contele
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    
volumes: 
    pgdata:
      driver: local
